### ISSUE TITLE
Crash when Ta Class attacked group

### ISSUE THREAD

**Issue by atnilla** [PinkaLulan/ShinColle#1]
http://pastebin.com/GyAGYz1H

Prior to the crash, I had setup a Tier 5 soul shards reborn zombie spawner to automate ship levelling, and failed to realized that I accidentally put Ta in wait mode. After dozens of zombies spawned, I got Ta to get into attack mode, she nuked the group of zombies, and promptly crashed my game, rendering it unloadable in all game modes. I'm unsure what exactly caused the problem, whether its the fact that a large number of mobs died at once or if the ships from Ta got damaged, but until I download world edit to try and fix the problem, the world is unable to be loaded.

**Comment by PinkaLulan** [comment]
It is a bug in target sorter, should be fixed in next version.
