### ISSUE TITLE
刷物品bug

### ISSUE THREAD

**Issue by SaintFall** [PinkaLulan/ShinColle#20]
成功率较低：在舰娘背包中放入要刷的物品，用附带火焰附加等武器击杀舰娘，当舰娘濒死时会有掉落物（舰娘蛋）和未死的舰娘，将舰娘蛋放置后重新生成舰娘，而GUI中物品还在。于是，变成了两只舰娘和双份的物品。
此bug在大陆舰娘服务器中已经泛滥。已经有人做出修复的mod版本来以此盈利http://w.yumc.pw/zc/ModRepairPack.html

望作者大人修复。
另外两个耐久不满的解体锤合成时会刷出更多的解体锤，望修复。

**Comment by PinkaLulan** [comment]
bug確認，嘗試修復中

**Comment by PinkaLulan** [comment]
已上傳1.7.10.rv26.1，修正bug。
