### ISSUE TITLE
Ticking Entity Error for 1.7.10 Modded

### ISSUE THREAD

**Issue by Airborne447** [PinkaLulan/ShinColle#21]
http://pastebin.com/69sCGND7

The crash occurs when I attempt to have a "Mob" version of any kind spawned beside "non-mob" variant. They will then fight and it will cause the crash.
This was tested in creative mode. 

Would like to add that I tried both rv26 and rv26.1 and both had the same isssue.

**Comment by PinkaLulan** [comment]
Some mod leaks class checking, I think this is not my fault.

-> at stacra.customtic.ActionsHandler.rangedhitEffect(ActionsHandler.java:104)

What is this mod?

**Comment by Airborne447** [comment]
Hmm. I'll check it out - I have no idea.
It's confirmed not to be Flans Mod/Warpdrive mods for the time being.
EDIT: Ah , Found the mod that causes the crash. It was "Custom-Tinkerer v.1.0.4". The projectiles had no issue with the mod removed , but when it was on , as soon as the black smoke from a torpedo of the Mob vesion spawns , the game would crash.

Thanks for leading me to find the source of the error. 
PS: Should've noticed that the creator of that mod was named "stacra" too, which matches the above line you mentioned.
