### ISSUE TITLE
NullPointerException on dedicated server

### ISSUE THREAD

**Issue by GSValore** [PinkaLulan/ShinColle#23]
**Description**:

When running on a dedicated server using Forge 2239, Minecraft 1.10.2, the mod will emit NullPointerExceptions and sometimes cause tick delays on heavily modded servers.  For testing, I created a minimal server with the mod and some utility mods to demonstrate the error.

**Result**:
Excerpt of the error: http://pastebin.com/7DrKsx0E
Full Log: http://pastebin.com/vjPZ4Y93

Last related line I could identify for the NPE: 
com.lulan.shincolle.capability.CapaTeitoku.sendSyncPacket(CapaTeitoku.java:1425)

P.S. the tick delays may only be related to the consistent errors thrown rather than another issue.  When testing by itself in single player, I saw no tick related issues.

**Comment by PinkaLulan** [comment]
bug confirmed, I will upload fixed version later
