### ISSUE TITLE
Gradle 相關檔案疑問

### ISSUE THREAD

**Issue by danny50610** [PinkaLulan/ShinColle#25]
你好

我發現你沒有將 Gradle 相關檔案放上去，像是：
```
gradle/wrapper/*
gradlew
gradlew.bat
build.gradle
```

比較重要的是`build.gradle`
如果有放上這些檔案，我想對於他人開發應該會比較方便

P.S 最近朋友推薦這個模組，才知道你有開發模組，之前都是看你在巴哈的教學

**Comment by PinkaLulan** [comment]
好喔
