### ISSUE TITLE
Hadal vortex rendering doesnt check FOV

### ISSUE THREAD

**Issue by Alessandro404** [PinkaLulan/ShinColle#33]
simply as that. Having a wider fov (i'm using 95) make the hadal vortex disappear too soon. Using 1.10.2.3.2 

![2017-05-28_17 12 36](https://cloud.githubusercontent.com/assets/8747581/26529861/e64ab600-43c8-11e7-837b-0278d6c5e766.png)

**Comment by Alessandro404** [comment]
after a bit of testing, it seems that the structure check if "seen" only with the heavy grudge block, is this right?

**Comment by PinkaLulan** [comment]
yes, the vortex model is apply on heavy grudge block only...
but i dont know why FOV affect the vortex rendering = =a

**Comment by PinkaLulan** [comment]
FOV checking box of hadal vortex model is expended 2 blocks in 4.0.
