### ISSUE TITLE
[question] [1.10.2] neutral ships spawning if ring check for non-boss ships is set to false

### ISSUE THREAD

**Issue by Alessandro404** [PinkaLulan/ShinColle#35]
If i remember correctly, when setting the same config to false in 1.7.10, the ships would spawn as enemies.
Now, without ring, they spawn but simply wander, as neutrals.

I don't know if its working exactly as planned, but maybe, a config for not checking the wedding ring for spawn AND neutrality?

**Comment by PinkaLulan** [comment]
Wild ship will not attack player in 1.10.2 but still attack player's ship actively.
It's a bug if they dont attack player's ship.

**Comment by Alessandro404** [comment]
I think I loved how I though back in 1.7.10 that small ships was assassins sent to kill me and my friends in our homes. I guess that this question coud became a feature request? :)

They were overpowered against iron swords, yes, but after a while having someone ready to sneak in to kill you was something that made our senses sharps and gave us something to build against (and a use for openmodularturrets lol)

**Comment by PinkaLulan** [comment]
ok I will make a config for aggressive AI.
