### ISSUE TITLE
[1.7.10] Feature Request

### ISSUE THREAD

**Issue by Xaikii** [PinkaLulan/ShinColle#37]
Hey I am using ShinColle in my modpack. While working with the Mobs I noticed some features I **personally** miss. 
So I would ask If it would be possible to add customization in terms of LvLing, Grudge Consumption,Atk/Health etc. for **individual** ShinColle and some more things.

First of all I want to say this Mod is actually pretty sweet, got actually nice feedback for adding this mod to my pack ^^'

But since my Mob Stats are "special" I'd like to have some options for individual ShinColles,

All my Ideas for Features:
Adding Customization of ever Single ShinColle (Config or MineTweaker).
Chaning the Consumptions (e.g. that some would need diamonds etc. to "work").
Customization of the LvLing System, how many LvLs, what/how much should be increased for every individual ShinColl, such as set Caps individual for every ShinColle.

[Optional] Adding an "Academy Craft" Support", that Modpack Devs can choose/set that some ShinColle are able to use specific skills from there.

I know modding takes its Time, so these are actually **general** Ideas.

**Comment by PinkaLulan** [comment]
Good ideas! But I dont update 1.7.10 anymore-.-

a feature can be implemented in 1.10.2:
config file for individual ship and equip attributes (including level limit)

And mod interaction things are too hard to me, I still can't get bees to work...

**Comment by Xaikii** [comment]
Sorry didn't know that you do not support 1.7.10 anymore.
Thought there is still a support since a new version of ShinColle came for 1.7.10 too ^^'

Well I think that feature would be still useful for others^^

Yeah do what you can.
Still I do not understand what you mean with "can't get bees to work", in 1.7.10 they worked perfectly, unless Forestry code changed to 1.10 everything should be fine ^^'
