### ISSUE TITLE
Problems with mining when out of Grudge

### ISSUE THREAD

**Issue by AileRozy** [PinkaLulan/ShinColle#42]
When ships run out Grudge while mining, they'll keep moving around and keep mining, but they won't stay where you told to, move randomly and sometimes go really far away.

艦娘怨念耗光時還在挖礦的話, 他們會繼續到處移動和挖礦, 但是他們不會待在指定地點而是隨機移動, 有時會走到非常遠

forge-1.10.2-12.18.3.2477
ShinColle-1.10.2.5.0
&have other mods

**Comment by PinkaLulan** [comment]
forget to check fuel...fix in next version
