### ISSUE TITLE
Incorrect Image/text/color in Abyssal Logbook [ShinColle-1.10.2.6.0]

### ISSUE THREAD

**Issue by AileRozy** [PinkaLulan/ShinColle#44]
Version ShinColle-1.10.2.6.0

![2018-01-03_01 39 27](https://user-images.githubusercontent.com/19416768/34494663-7a7e0fb0-f02c-11e7-9d14-f20fbef175d0.png)
![2018-01-03_01 39 31](https://user-images.githubusercontent.com/19416768/34494669-7f222448-f02c-11e7-80f4-96ad2e03545e.png)

Abyssal Crane had wrong image and Crafting Recipe didn't have one, this problem also found in en_US
深海起重機合成圖片錯誤而合成配方卻沒有合成圖, 這問題在英文版也一樣

incorrect colors:
該頁面第10條白色文字似乎不該是白色, 又如果真是白色會看不清文字
![2018-01-03_02 05 20](https://user-images.githubusercontent.com/19416768/34494683-8f750bd0-f02c-11e7-9838-3ddae294743e.png)

![2018-01-03_02 04 41](https://user-images.githubusercontent.com/19416768/34494687-92cc8060-f02c-11e7-9762-e01c2708d992.png)

失明兩字應該是紅色的

**Comment by PinkaLulan** [comment]
感謝回報下一版修正 

    Aile Rozy <notifications@github.com> 於 2018/1/3 (週三) 2:24 AM 寫道﹕
 

 Version ShinColle-1.10.2.6.0
Abyssal Crane had wrong image and Crafting Recipe didn't have one, this problem also found in en_US
深海起重機合成圖片錯誤而合成配方卻沒有合成圖, 這問題在英文版也一樣incorrect colors:
該頁面第10條白色文字似乎不該是白色, 又如果真是白色會看不清文字
失明兩字應該是紅色的—
