### ISSUE TITLE
Crafting recipe(item) issue[ShinColle-1.10.2.6.0]

### ISSUE THREAD

**Issue by AileRozy** [PinkaLulan/ShinColle#45]
測試環境:
forge-1.10.2-12.18.3.2511
ShinColle-1.10.2.6.0
無其他mod
.

合成配方(道具)在合成表 左上角第一格 以外的空格沒有填滿的情況, 第一格的物品會沒有出現在道具描述上或完全無法記錄到合成配方上, 沒出現在描述不影響合成, 無法記錄到合成配方的情況會導致艦娘無法進行合成

另, 艦娘等級不足20 (19以下) 的情況會無法進行合成, 請問這是設定嗎?

**Comment by PinkaLulan** [comment]
感謝回報 
這兩個問題都已修正
