### ISSUE TITLE
Ship-chan cant damage enemy shipgirl

### ISSUE THREAD

**Issue by Danek9t** [PinkaLulan/ShinColle#46]
Can u help me with this?
i cant seem to work out why it couldn't damage the enemy ship, i have tried in creative and new map but the result is still the same, equip them with both enchanted equipment and non enchanted equipment too.

**Comment by PinkaLulan** [comment]
Tatsuta and Ro500 are bug now, fix next version.

**Comment by Danek9t** [comment]
hope you not planning to only do the 1.12.1 version only,pls do keep update
1.10.2 updated too

**Comment by PinkaLulan** [comment]
fixed in 1.10.2.7.1
