### ISSUE TITLE
Problem with ShinColle and Morph

### ISSUE THREAD

**Issue by demycat** [PinkaLulan/ShinColle#47]
I noticed such a problem, when I want to take the ship, I need to hit it with a hammer and then its spawner appears, but there is a problem, for example, if there are no Re-class ship for example, then the spawner does not drop out, but if it does, then the spawner falls out accordingly!
How do I fix this problem ?!

**Comment by PinkaLulan** [comment]
morph acquire method changed in 1.10.2.7.1

**Comment by demycat** [comment]
@PinkaLulan it's in version 0.9.3(minecraft 1.7.10)
