### ISSUE TITLE
Revised en_US.lang

### ISSUE THREAD

**Issue by nodatahere** [PinkaLulan/ShinColle#53]
I've taken some time to try my hand at revising the English language file. Due to Github disallowing the upload of *.lang files for issues, I've renamed the revision to [en_US.lang.txt](https://github.com/PinkaLulan/ShinColle/files/2037985/en_US.lang.txt) for upload. This is only the first revision, and I will continue revising further based on the feedback I recieve.

**Comment by AileRozy** [comment]
You can try to use pull requests to help author update the file

**Comment by nodatahere** [comment]
I tried multiple times, but the dialogue for opening the PR kept asking me to make a new branch for the PR and telling me that I didn't have sufficient permission to make said branch when I tried to do that.

Edit: After looking at the repository network and the closed pull requests, I've figured out what I was doing wrong.
